Forum/Controllers/AuthController.cs
using Forum.Controllers.Helpers;
using Forum.Exceptions;
using Forum.Models.Views;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Forum.Controllers
{
    public class AuthController : Controller
    {
        private readonly AuthenticationHelper authenticationHelper;

        public AuthController(AuthenticationHelper authenticationHelper)
        {
            this.authenticationHelper = authenticationHelper;

        }
        public IActionResult Login()
        {
            var login = new LoginViewModel();
            return View(login);
        }

        public IActionResult Register()
        {
            return RedirectToAction("Create", "Users");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login([Bind("Username, Password")] LoginViewModel loginUser)
        {
            if (!ModelState.IsValid)
            {
                return View(loginUser);
            }
            try
            {
                var user = authenticationHelper.TryGetUser(loginUser.Username, loginUser.Password);

                this.HttpContext.Session.SetString("CurrentUser", user.Username);
                this.HttpContext.Session.SetString("CurrentUserRole", user.Role.ToString());
                this.HttpContext.Session.SetString("CurrentUserId", user.Id.ToString());
                return RedirectToAction("Index", "Home");
            }
            catch (UnauthorizedOperationException ex)
            {
                //logger.LogError(ex, "Unauthorized operation by user {0}", username);
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(loginUser);
            }
        }
    }
}

Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Forum</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-dark text-light">
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 text-light">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Forum</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a href="/swagger/index.html" class="nav-link text-light">Swagger</a>
						</li>
						@if (this.Context.Session.GetString("CurrentUserRole") != null)
						{
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
						</li>
							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; @DateTime.Now.Year - Forum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>